### ISSUE TITLE
Possible mistake in documentation

### ISSUE THREAD

**Issue by kevingeorget** [sarneeh/casbin-knex-adapter#239]
Hello,  

First of all thank you for this Knex adapter.

It seems there is an error in the documentation example.  
` const adapter = await KnexAdapter.newAdapter({ knex });` should be replaced by 
` const adapter = await KnexAdapter.newAdapter(knex);`  

This PR fixes the problem: https://github.com/knex/casbin-knex-adapter/pull/240

**Comment by transtone** [comment]
thx [kevingeorget](https://github.com/kevingeorget)

```js
import Knex from 'knex'
import { KnexAdapter } from 'casbin-knex-adapter'

const knex = Knex({
    client: 'pg',
    connection: {
      host: process.env.PG_HOST,
      port: Number(process.env.PG_PORT),
      user: process.env.PG_USERNAME,
      password: process.env.PG_PASSWORD,
      database: process.env.PG_DATABASE,
    },
  })
const a = await KnexAdapter.newAdapter(knex)
const e = await newEnforcer('modal.conf path', a)
```
